services:
  web:
    container_name: fastapi_web_dev
    build:
      context: .
      target: runtime
    volumes:
      - ./:/app:delegated
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env.dev
    depends_on:
      db-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
      rabbitmq-dev:
        condition: service_healthy
    networks:
      - appnet_dev

  worker:
    container_name: fastapi_worker_dev
    build:
      context: .
      target: runtime
    volumes:
      - ./:/app:delegated
    command: celery -A app.tasks.worker.celery_app worker --loglevel=info --concurrency=2
    env_file: .env.dev
    depends_on:
      db-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
      rabbitmq-dev:
        condition: service_healthy
    networks:
      - appnet_dev

  db-dev:
    container_name: fastapi_db_dev
    image: postgres:15
    environment:
      POSTGRES_DB: fastapi_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - appnet_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-dev:
    container_name: fastapi_redis_dev
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq-dev:
    container_name: fastapi_rabbitmq_dev
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet_dev
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  appnet_dev:
    driver: bridge
    name: fastapi_dev_network

volumes:
  postgres_data_dev: