"""initial clean state

Revision ID: cc50e86df77d
Revises: 
Create Date: 2025-09-20 19:43:50.879836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc50e86df77d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_items_id'), 'new_items', ['id'], unique=False)
    op.create_index(op.f('ix_new_items_name'), 'new_items', ['name'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_new_items_name'), table_name='new_items')
    op.drop_index(op.f('ix_new_items_id'), table_name='new_items')
    op.drop_table('new_items')
    # ### end Alembic commands ###
